name: plankton

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]


jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Run a one-line script
        run: echo Hello, world!

      - name: Run a multi-line script
        run: 
        gem install bundler
        bundle install --jobs 4 --retry 3
      - name: Deploy site
        run: bundle exec rake site:publish
        env:
         GH_PAGES_TOKEN: ${{ secrets.GH_PAGES_TOKEN }} 
